name: Functions testing
on: push

jobs:
  function_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Function testing
        run: |
          echo ${{ contains( 'hello', 'll' ) }}
          echo ${{ startsWith( 'hello', 'he' ) }}
          echo ${{ endsWith( 'hello', 'lo' ) }}
          echo ${{ format( 'Hello {0} {1} {2}', 'World', '!', ':D' ) }}
